# Generated by Django 4.2.5 on 2023-09-18 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entrada', '0003_mensage'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensage',
            name='id_user',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
