# Generated by Django 4.2.5 on 2023-09-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entrada', '0005_user_email_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
