# Generated by Django 4.2.5 on 2023-10-04 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entrada', '0010_mensage_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
