# Generated by Django 4.2.6 on 2023-10-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entrada', '0015_alter_mensage_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensage',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
