# Generated by Django 4.2.6 on 2023-10-24 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entrada', '0016_alter_mensage_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensage',
            name='id',
            field=models.DecimalField(decimal_places=0, max_digits=20, primary_key=True, serialize=False),
        ),
    ]
