# Generated by Django 4.2.5 on 2023-11-18 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entrada', '0017_alter_mensage_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensage',
            name='mensage',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
